version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout      

      - run:
          name: install dependencies
          command: |
            # conda env create -q || conda env update -q
            # source activate adj
            conda install -c conda-forge parameterized
            conda install -y xtb
            conda install -qy conda-build anaconda-client pytest pytest-cov

      - run:
          name: run tests
          command: |
            # source activate adj
            pytest --color=yes -v --cov=uxtbpy tests
            conda install -c conda-forge codecov
            codecov -t baeb0957-f5cc-47a5-8f10-43e4227bb498

      - store_artifacts:
          path: test-reports
          destination: test-reports
